endpoints:
  all:
    enabled: true
    path: "/management"
    sensitive: false
micronaut:
  application:
    name: timeTraveller
netty:
  default:
    allocator:
      max-order: 3
restapi:
  hateoas:
    filter:
      enabled: true
